---
title: "Ali Zahreddine"
output:
  html_document: default
date: "2022-08-30"
---





# <span style="color: purple;">BellaBeat Smart Device Analysis </span>

**Hi! My name is Ali and I am sharing my first case study for the Google Data Analytics Certification Program. For this project, i was assigned to work with the marketing analytics team as a junior data analyst, studying Bellabeats smart device usage.**
<br>
<br>


#### <span style="color: purple;">BellaBeat </span> is a high-tech manufacturer of health-focused products for women.
<br>

* **<span style="color: purple;">BellaBeat </span>**: The Bellabeat app provides users with health data related to their activity, sleep, stress, menstrual cycle, and mindfulness habits. This data can help users better understand their current habits and make healthy decisions. The Bellabeat app connects to their line of below smart wellness products.
* **<span style="color: purple;">Leaf </span>**: Wellness tracker can be worn as a bracelet, necklace, or clip which tracks activity, sleep, and stress.
* **<span style="color: purple;">Time </span>**: Smart watch with activity, sleep, and stress tracker.
* **<span style="color: purple;">Spring </span>**:Water bottle with water intake tracker.
<br>

## ![](https://uspto.report/TM/97125685/mark.png){width=30%}
<br>
<br>

# **<span style="color: purple;">Key Stakeholders </span>**
<br>
* **<span style="color: purple;">Urška Sršen </span>**:Bellabeat’s co-founder and Chief Creative Officer.
<br>
* **<span style="color: purple;">Sando Mur </span>**:Mathematician and Bellabeat’s cofounder; key member of the Bellabeat executive team.
<br>
* **<span style="color: purple;">Bellabeat marketing analytics team </span>**:A team of data analysts responsible for collecting, analyzing, and reporting data that helps guide Bellabeat’s marketing strategy.
<br>
<br>

# **<span style="color: purple;">Ask (Business Task) </span>** 
<br>

##### 1- What are some trends in smart device usage?
##### 2- How could these trends apply to Bellabeat customers ?
##### 3- How would these trends help influence a marketing strategy ?

<br>
<br>

# **<span style="color: purple;">Prepare (Data) </span>**
#### **<span style="color: purple;">Data Source: </span>**
<br>

* The main data source used for this analysis is: [Fitbit Fitness Tracker Data](https://www.kaggle.com/datasets/arashnic/fitbit) 

* 18 .csv files uploaded by Data Scientist Möbius, containing personal fitness and health data for 33 distinct users (Minutes level output for physical activity, heart rate, sleep).
[.CSV1](https://docs.google.com/spreadsheets/d/1ZWdF8PVhQqD0AOl2ANz4quo7XVUEQfNZmrUn0MUaXPs/edit#gid=1782381495), [.CSV2](https://docs.google.com/spreadsheets/d/1ZNx2f0-aTugowMcmePKbpe3na2kz9HE30G6C8Il6YHU/edit#gid=44708024), [.CSV3](https://docs.google.com/spreadsheets/d/1VEmGHatyjFCTChLVGJD-7PzqYCtkRKfW0M5qL06ot10/edit#gid=190457415), [.CSV4](https://docs.google.com/spreadsheets/d/1H1zNep2uwzhfOcI38pD4UxtwilEbKCgdgWZPrp1ANjI/edit#gid=1503302649), [.CSV5](https://docs.google.com/spreadsheets/d/12lV5jpM4OJD9WwBG9ES6Dxp9pKW2DwwU7tNjIih4tcE/edit#gid=1033004841), [.CSV6](https://docs.google.com/spreadsheets/d/13KP5rfQYHqy3XJo-EsfvooBqA2r_Hk5pyXjbOr9zBFk/edit#gid=528214585), [.CSV7](https://docs.google.com/spreadsheets/d/1P8j-fgxJzPX5t6bSoLLftq1Tk_yQ5SUNaf5vw9_jNQo/edit#gid=614846439), [.CSV8](https://docs.google.com/spreadsheets/d/1bH3U4sN7YpVrB1XuSZmWwKliLyIrePQ82VK4QTGmf0Y/edit#gid=274277267), [.CSV9](https://docs.google.com/spreadsheets/d/1llGYKPoLs60T6vG3a1I9Dd_ySnhNZiWs9-ZzzihE8Ds/edit#gid=529848060), [.CSV10]( https://docs.google.com/spreadsheets/d/1p58lhPdF_rKy8yF2XaHUHfwpJjPGZpRJRvbGOb1y4aU/edit#gid=366649586), [.CSV11](https://docs.google.com/spreadsheets/d/1rwICv-lOrjlkhpT9fMUdF6t9gqjTww8dUAaCZRK1hRA/edit#gid=670075440), [.CSV12](https://docs.google.com/spreadsheets/d/1h1eiYFtLBIFZJOTl1-SsSlQDJS91lcJNfSzgrz5UoeQ/edit#gid=703354650), [.CSV13](https://docs.google.com/spreadsheets/d/1JkLqdDNJ9ca217oX5cjknwjwAcNSaoP0qzhXNOt8u1k/edit#gid=1226586714), [.CSV14](https://docs.google.com/spreadsheets/d/1O_PP7dbVxT2_pRtPmpM4mD_xVnUI1crC3-MlZS-Nsro/edit#gid=457140088), [.CSV15](https://docs.google.com/spreadsheets/d/1yLRck3x35OlhaVKMJuJTTwLF_hQdaUpXKesk4y2dDbM/edit#gid=1964339960), [.CSV16](https://docs.google.com/spreadsheets/d/1DBXltoQbOFSuYFbnVj4mM96-Q1vneOmfY1NEuGjqUb4/edit#gid=1709609303), [.CSV17](https://docs.google.com/spreadsheets/d/1UpQ2-wtcpNR7HgO7rekW7KXRyVmorlSOEIex3nbQONc/edit#gid=570530554), [.CSV18](          https://docs.google.com/spreadsheets/d/1KNE4JyrbXmuNTwZyDqiU3J2vk4hZmbDzv1rFfBo0--0/edit#gid=578957315)
<br>
<br>

#### **<span style="color: purple;">Accessibility, privacy and usage of data: </span>** 

The data sets were generated by respondents who took part in a distributed survey via Amazon Mechanical Turk between 03.12.2016 and 05.12.2016 and were first uploaded on the open science platform [Zenodo](https://about.zenodo.org/), see Furberg, R., Brinton, J., Keating, M., & Ortiz, A. (2016). Crowd-sourced Fitbit datasets 03.12.2016-05.12.2016 [Data set]. Zenodo. https://doi.org/10.5281/zenodo.53894.

The data is licensed under [Creative Commons Attribution 4.0 International](https://creativecommons.org/licenses/by/4.0/).

A data dictionary for FitBit data is available from [Fitbase](https://www.fitabase.com/resources/knowledge-base/exporting-data/data-dictionaries/).
<br>
<br>

#### **<span style="color: purple;">Data integrity and limitations: </span>**

* Small sample size (33 users).
* Old data (2016), Short timeframe (31 days period).
* Sleep data is missing for some users.
* Heart rate data is missing for some users.
* Data shortage(Age, Demographic information).
* Data is not from a Primary source.
<br>

# **<span style="color: purple;">Process (Data) </span>**

**Data was cleaned, organized, analyzed and visualized using R programming.**
<br>
<br>

```{r loading packages, message=FALSE, warning=FALSE, paged.print=TRUE}
# loading packages
library(here)
library(skimr)
library(janitor)
library(tidyverse)
library(stringi)
library(lubridate)
library(ggplot2)
library(readr)
library(ggrepel)
library(dplyr)
```

### <span style="color: red;">Import Data </span>
**Data sets used**: *Daily Activity, Daily Sleep, Hourly Calories, Hourly Intensities, Hourly Steps, Heart Rate Seconds, and Weight Log.*

```{r Importing Data, message=FALSE, warning=FALSE}
# Importing Data
Daily_Activity <- read.csv("dailyActivity_merged.csv")
Daily_Sleep <- read.csv("sleepDay_merged.csv")
Hourly_Calories <- read.csv("hourlyCalories_merged.csv")
Hourly_Intensities <- read.csv("hourlyIntensities_merged.csv")
Hourly_Steps <- read.csv("hourlySteps_merged.csv")
Heart_Rate <- read.csv ("heartrate_seconds_merged.csv")
Weight <- read.csv("weightLogInfo_merged.csv")

```

### <span style="color: purple;">Data Preview </span>
*Overview of each Data set using various functions.*

* **<span style="color: purple;"> head() </span>**: Shows the first (by default) 6  rows present in the input data frame.
* **<span style="color: purple;"> dim() </span>**: Shows the dimensions of the data frame by row and column.
* **<span style="color: purple;"> str() </span>**: Shows the structure of the data frame.
* **<span style="color: purple;"> colnames() </span>**: Shows the name of each column in the data frame.
* **<span style="color: purple;"> glimpse() </span>**: Makes it possible to see every column in a data frame.
* **<span style="color: purple;"> tail() </span>**: Shows the last 6 rows of the data frame.

**<span style="color: red;"> Daily_Activity </span>**

```{r message=FALSE, warning=FALSE}
head(Daily_Activity)
str(Daily_Activity)
dim(Daily_Activity)
colnames(Daily_Activity)
glimpse(Daily_Activity)
tail(Daily_Activity)
```


**<span style="color: red;"> Daily_Sleep </span>**

```{r message=FALSE, warning=FALSE}
head(Daily_Sleep)
str(Daily_Sleep)
dim(Daily_Sleep)
colnames(Daily_Sleep)
glimpse(Daily_Sleep)
tail(Daily_Sleep)
```


**<span style="color: red;"> Hourly_Calories </span>**

```{r message=FALSE, warning=FALSE}
head(Hourly_Calories)
str(Hourly_Calories)
dim(Hourly_Calories)
colnames(Hourly_Calories)
glimpse(Hourly_Calories)
tail(Hourly_Calories)
```


**<span style="color: red;"> Hourly_Intensities </span>**

```{r message=FALSE, warning=FALSE}
head(Hourly_Intensities)
str(Hourly_Intensities)
dim(Hourly_Intensities)
colnames(Hourly_Intensities)
glimpse(Hourly_Intensities)
tail(Hourly_Intensities)
```


**<span style="color: red;"> Hourly_Steps </span>**

```{r message=FALSE, warning=FALSE}
head(Hourly_Steps)
str(Hourly_Steps)
dim(Hourly_Steps)
colnames(Hourly_Steps)
glimpse(Hourly_Steps)
tail(Hourly_Steps)
```


**<span style="color: red;"> Heart_Rate  </span>**

```{r message=FALSE, warning=FALSE}
head(Heart_Rate)
str(Heart_Rate)
dim(Heart_Rate)
colnames(Heart_Rate)
glimpse(Heart_Rate)
tail(Heart_Rate)
```

**<span style="color: red;"> Weight  </span>**

```{r message=FALSE, warning=FALSE}
head(Weight)
str(Weight)
dim(Weight)
colnames(Weight)
glimpse(Weight)
tail(Weight)
```


### <span style="color: purple;">Data Cleaning</span>
After previewing the data sets we noticed the following: 

* *Column names needs cleaning*
* *Dates are in the wrong format (chr)*

**<span style="color: red;"> Check for unique Ids in each data set:  </span>** 

```{r message=FALSE, warning=FALSE}
n_unique(Daily_Activity$Id)
n_unique(Daily_Sleep$Id)
n_unique(Hourly_Calories$Id)
n_unique(Hourly_Intensities$Id)
n_unique(Hourly_Steps$Id)
n_unique(Heart_Rate$Id)
n_unique(Weight$Id)
```


**<span style="color: red;"> Check for duplicated data in each data set:  </span>** 

```{r message=FALSE, warning=FALSE}
sum(duplicated(Daily_Activity))
sum(duplicated(Daily_Sleep))
sum(duplicated(Hourly_Calories))
sum(duplicated(Hourly_Intensities))
sum(duplicated(Hourly_Steps))
sum(duplicated(Weight))
## sum of duplicated data in the 'Heart Rate' data set is 0.

```

*--> Data duplicates detected in the Daily Sleep Data set.*

**<span style="color: red;"> Remove duplicates:  </span>**

```{r message=FALSE, warning=FALSE}
Daily_Sleep <- Daily_Sleep %>%
distinct() %>%
drop_na()
```

**<span style="color: red;"> Verify duplicate removal  </span>**

```{r message=FALSE, warning=FALSE}
sum(duplicated(Daily_Sleep))
```

**<span style="color: red;"> Clean and Rename columns for consistency  </span>**

```{r message=FALSE, warning=FALSE}
Daily_Activity <- clean_names(Daily_Activity)
Daily_Sleep <- clean_names(Daily_Sleep)
Hourly_Calories <- clean_names(Hourly_Calories)
Hourly_Intensities <- clean_names(Hourly_Intensities)
Hourly_Steps <- clean_names(Hourly_Steps)
Heart_Rate <- clean_names(Heart_Rate)
Weight <- clean_names(Weight)
```

**<span style="color: red;"> Date and time formatting </span>**

```{r message=FALSE, warning=FALSE}
Daily_Activity$activity_date=as.POSIXct(Daily_Activity$activity_date,format ="%m/%d/%Y" , tz=Sys.timezone())
Daily_Sleep$sleep_day=as.POSIXct(Daily_Sleep$sleep_day, format = "%m/%d/%Y %I:%M:%S %p",tz = Sys.timezone())
Hourly_Calories$activity_hour=as.POSIXct(Hourly_Calories$activity_hour, format = "%m/%d/%Y %I:%M:%S %p",tz = Sys.timezone())
Hourly_Intensities$activity_hour=as.POSIXct(Hourly_Intensities$activity_hour, format = "%m/%d/%Y %I:%M:%S %p",tz = Sys.timezone())
Hourly_Steps$activity_hour=as.POSIXct(Hourly_Steps$activity_hour, format = "%m/%d/%Y %I:%M:%S %p",tz = Sys.timezone())
Heart_Rate$time=as.POSIXct(Heart_Rate$time,format ="%m/%d/%Y %I:%M:%S %p" , tz=Sys.timezone())
Weight$date=as.POSIXct(Weight$date,format ="%m/%d/%Y" , tz=Sys.timezone())

```

```{r message=FALSE, warning=FALSE}
# Generating 4 unique ids
step_id <- unique(Daily_Activity$id,incomparables = FALSE)
sleep_id <- unique(Daily_Sleep$id,incomparables = FALSE)
heartrate_id <- unique(Heart_Rate$id,incomparables = FALSE)
weight_id <- unique(Weight$id,incomparables = FALSE)
```


# **<span style="color: purple;">Analyze (Data) </span>**
<span style="color: red;">**Number of users using each feature**: </span>

```{r message=FALSE, warning=FALSE}
step_id_count <- length(step_id)
sleep_id_count <- length(sleep_id)
heartrate_id_count <- length(heartrate_id)
weight_id_count <- length(weight_id)
#Adding vectors to the data frame

row_names <- c("Step","Sleep","Heartrate","Weight")  
id_count <- c(step_id_count,sleep_id_count,heartrate_id_count,weight_id_count)
id_dataframe <- data.frame(row_names,id_count)
```

**<span style="color: red;">Bar graph showing feature vs user  </span>**
```{r message=FALSE, warning=FALSE}
ggplot(data=id_dataframe,mapping=aes(x=row_names,y=id_count,fill=row_names)) + 
  geom_col()+ 
  labs(title = "Number of Users using each Feature",x="Feature", y="Users")+
   theme(axis.title.x=element_text(colour="red"))+
   theme(axis.title.y=element_text(colour="red"))+
   theme(plot.title = element_text(color = "red"))
```
<br>
The activity data is automatically tracked by the device. Steps can be manually entered by participants, but all fitness trackers support algorithmic step detection. Sleep data and heart rate data is less frequently available. One reason could be, that different devices were used tracking the data.



### **<span style="color: red;">Statistical summary </span>**
```{r message=FALSE, warning=FALSE}
Daily_Activity %>% 
  select(total_steps, total_distance, calories, very_active_minutes, fairly_active_minutes, lightly_active_minutes,sedentary_minutes) %>% 
  summary()

Daily_Sleep %>% 
  select(total_sleep_records, total_minutes_asleep,total_time_in_bed) %>% 
  summary()

Hourly_Calories %>% 
  select(calories) %>% 
  summary()

Hourly_Intensities %>% 
  select(total_intensity) %>% 
  summary()

Hourly_Steps %>% 
  select(step_total) %>% 
  summary

Weight %>% 
  select(weight_kg) %>% 
  summary()
```

### **<span style="color: red;">Data merging </span>**
```{r message=FALSE, warning=FALSE}
merge_data_calories_intensities <- merge(Hourly_Calories,Hourly_Intensities, by = c('id', 'activity_hour'))
# Check merged data
head(merge_data_calories_intensities)
# Fixing date format
Daily_Activity$activity_date=as.POSIXct(Daily_Activity$activity_date, format="%m/%d/%Y", tz=Sys.timezone())
Daily_Activity$date <- format(Daily_Activity$activity_date, format = "%m/%d/%y")

Daily_Sleep$sleep_day=as.POSIXct(Daily_Sleep$sleep_day, format="%m/%d/%Y %I:%M:%S %p", tz=Sys.timezone())
Daily_Sleep$date <- format(Daily_Sleep$sleep_day, format = "%m/%d/%y")

merge_daily_activity <- merge(x = Daily_Activity, y = Daily_Sleep, by = c ("id", "date"), all.x = TRUE)
# Check merged data
head(merge_daily_activity)

# Transforming data per weekday 
merge_daily_activity <- transform(merge_daily_activity, Weekday = weekdays(activity_date))
# Check merged data
glimpse(merge_daily_activity)
```

### **<span style="color: red;">Categorizing user's usage  </span>**
```{r message=FALSE, warning=FALSE}

user_daily <- Daily_Activity %>% 
  filter (total_steps > 200) %>% 
  group_by(id) %>% 
  summarize(activity_date = sum(n())) %>% 
  mutate(usage = case_when(
    activity_date >= 1 & activity_date <= 14 ~ "low use",
    activity_date >= 15 & activity_date <= 21 ~ "moderate use",
    activity_date >= 22 & activity_date <= 31 ~"high use"
  )) %>% 
  mutate(usage = factor(usage, level = c('low use', 'moderate use', 'high use'))) %>% 
  group_by(usage)
# Check data
head(user_daily)

precent_usage <- Daily_Activity %>% 
  left_join(user_daily, by = 'id') %>% 
  group_by(usage) %>% 
  summarize(users = n_distinct(id)) %>% 
  mutate(percent = users / sum(users)) %>% 
  arrange(percent) %>% 
  mutate( percent = scales::percent(percent))
# Check data
head(precent_usage)
```

# **<span style="color: red;">Pie Chart reflecting the distribution of users  </span>**

```{r message=FALSE, warning=FALSE}
ggplot(precent_usage,aes(fill=usage,y = users,x = "")) +
  geom_bar(stat = "identity", width = 1, color = "black") +
  coord_polar("y", start = 0) +
  theme_void() +
  theme(axis.title.x= element_blank(),
        axis.title.y = element_blank(),
        panel.border = element_blank(), 
        panel.grid = element_blank(), 
        axis.ticks = element_blank(),
        axis.text.x = element_blank(),
        plot.title = element_text(hjust = 0.5, vjust = -5, size = 15, face = "bold")) +
  geom_text(aes(label = percent, x=1.2),position = position_stack(vjust = 0.5)) +
  labs(title = "Activity Usage Group Distribution", caption = "Data Source: Fitbit Fitness Tracker Data")+
  theme(plot.title = element_text(color = "red"))+
  theme(plot.caption = element_text(color="red"))+
  guides(fill = guide_legend(title = "Usage Type"))+
  scale_fill_brewer(palette = "Purples" )
```
<br>
* <span style="color: red;">**73% of users are high usage type, were only 6% of users are considered low usage type.**</span>
<br>

**Claculating the averages for: <span style="color: red;">Steps, </span> <span style="color: red;">Calories,  </span> <span style="color: red;">Sleep.(Daily)**
```{r message=FALSE, warning=FALSE}
daily_averages <- merge_daily_activity %>% 
  group_by(id) %>% 
  summarize(average_daily_steps=mean(total_steps),average_daily_calories=mean(calories),
            average_daily_sleep=mean(total_minutes_asleep))
```

**Classify daily users for: <span style="color: red;">Sedentary,  </span> <span style="color: red;">Active,  </span> and <span style="color: red;">Highly active </span>.**
```{r message=FALSE, warning=FALSE}
user_breakdown <- daily_averages %>% 
  mutate(type_of_user=case_when(
    average_daily_steps<5000~"Sedentary",
    average_daily_steps>=5000 & average_daily_steps<10000~"Active",
    average_daily_steps>=10000~"Highly Active"))
```

<span style="color: red;">**User breakdown in percentages** </span>
```{r message=FALSE, warning=FALSE}
user_breakdown_percent <- user_breakdown %>% 
  group_by(type_of_user) %>% 
  summarise(users=n_distinct(id)) %>% 
  mutate(percentage=users/sum(users)) %>% 
  arrange(percentage) %>% 
  mutate(percentage=scales::percent(percentage))
```

<span style="color: red;">**Chart for user breakdown** </span>
```{r message=FALSE, warning=FALSE}
ggplot(user_breakdown_percent,aes(x=type_of_user,y=users))+
  geom_segment(aes(x=type_of_user,xend=type_of_user,y=0,yend=users),color="red",lwd=2)+
  geom_point(size=8.75,color="red")+
  geom_text(aes(label=percentage),color="white",size=2.50)+
  labs(title = "Daily Use Breakdown",x="Type of User",y="Number of users")+
  theme(axis.title.x=element_text(colour="red"))+
   theme(axis.title.y=element_text(colour="red"))+
   theme(plot.title = element_text(color = "red"))

```

<span style="color: red;">**Checking for correlations** </span>
```{r echo=TRUE, message=FALSE, warning=FALSE}
ggplot(data = Daily_Activity, aes(x = total_steps, y = calories)) +
  geom_point(colour="red") + geom_smooth() + labs(title = "Total Steps vs Calories")+
  theme(axis.title.x=element_text(colour="red"))+
   theme(axis.title.y=element_text(colour="red"))+
   theme(plot.title = element_text(color = "red"))
  
 ggplot(data = Daily_Activity, aes(x = total_distance, y = calories)) +
  geom_point(colour="green") + geom_smooth() + labs(title = "Total Distance vs Calories")+
   theme(axis.title.x=element_text(colour="red"))+
   theme(axis.title.y=element_text(colour="red"))+
   theme(plot.title = element_text(color = "red"))

ggplot(data = Daily_Activity, aes(x = very_active_minutes, y = calories)) +
  geom_point(colour="purple") + geom_smooth()+ labs(title = "Total Very Active Minutes vs Calories")+
  theme(axis.title.x=element_text(colour="red"))+
   theme(axis.title.y=element_text(colour="red"))+
   theme(plot.title = element_text(color = "red"))

ggplot(data = Daily_Activity, aes(x = fairly_active_minutes, y = calories)) +
  geom_point(colour="orange") + geom_smooth()+ labs(title = "Total Fairly Active Minutes vs Calories")+
  theme(axis.title.x=element_text(colour="red"))+
   theme(axis.title.y=element_text(colour="red"))+
   theme(plot.title = element_text(color = "red"))

ggplot(data = merge_daily_activity, aes(x =  total_minutes_asleep , y = total_steps)) +
  geom_point(colour="gold") + geom_smooth()+ labs(title = "Total Steps vs Minutes asleep")+
  theme(axis.title.x=element_text(colour="red"))+
   theme(axis.title.y=element_text(colour="red"))+
   theme(plot.title = element_text(color = "red"))

ggplot(data = merge_daily_activity, aes(x =  sedentary_minutes  , y = total_minutes_asleep)) +
  geom_point(colour="pink") + geom_smooth()+ labs(title = "Total Sedentary Minutes vs Minutes a Sleep")+
  theme(axis.title.x=element_text(colour="red"))+
   theme(axis.title.y=element_text(colour="red"))+
   theme(plot.title = element_text(color = "red"))
```


<span style="color: red;">**Analyzing active weekdays** </span> 

```{r}
#adding a day of the week column to daily activity table
new_daily_activity <- Daily_Activity %>% 
  mutate(day=weekdays(activity_date))

colnames(Daily_Sleep)[2] <- "activity_date"
daily_sleep_activity <- merge(new_daily_activity,Daily_Sleep, by=c("id","activity_date"))

#A column to convert minutes to hours
weekday_steps_sleep <- daily_sleep_activity %>%
  group_by(day) %>% 
  summarise(average_steps=mean(total_steps),average_sleep=mean(total_minutes_asleep)) %>% 
  mutate(hours=average_sleep/60)
weekday_steps_sleep<- weekday_steps_sleep%>% 
  mutate(day=ordered(weekday_steps_sleep$day, 
                     levels=c("Monday", "Tuesday", 
                              "Wednesday", "Thursday",
                              "Friday", "Saturday", "Sunday")))

 
#Bar plot to show the average steps per day

ggplot(data=weekday_steps_sleep,mapping = aes(x=day,y=average_steps))+
  geom_col(fill="blue")+ 
  geom_hline(yintercept = 7500) +
  labs(title = "Average Steps per Day",x="Day",y="Steps")+
  guides(fill="none")+
  theme(axis.title.x=element_text(colour="red"))+
   theme(axis.title.y=element_text(colour="red"))+
   theme(plot.title = element_text(color = "red"))
#Bar plot to show the average steps per day
ggplot(data=weekday_steps_sleep,mapping = aes(x=day,y=hours))+
  geom_col(fill="red")+ 
  geom_hline(yintercept = 8) +
  labs(title = "Average Sleep per Day",x="Day",y="Hours Asleep")+
  guides(fill="none")+
  theme(axis.title.x=element_text(colour="red"))+
   theme(axis.title.y=element_text(colour="red"))+
   theme(plot.title = element_text(color = "red"))
```
<br>
<br>
* **No users are hitting the daily steps target.**
* **No users are hitting the recommended sleep hours.**
<br>

```{r message=FALSE, warning=FALSE, include=FALSE}
# Creating a new timeframe
hourly_total <- Hourly_Calories %>% 
  left_join(Hourly_Intensities,by=c("id","activity_hour")) %>% 
  left_join(Hourly_Steps,by=c("id","activity_hour")) %>%
  separate(activity_hour,into = c("date","time"),sep = " ") %>% 
  mutate(day = format(ymd(date), format = '%A')) %>% 
  mutate(time=format(parse_date_time(as.character(time), "HMS"), format = "%H:%M")) %>% 
  mutate(date= as.POSIXct(date))

#reorder columns so that day is next to date
hourly_total <- hourly_total[,c(1,2,8,3:7)]



#what time during day are users most active
library(viridis)

```

<span style="color: red;">**Analyzing the time of activity during days** </span>
```{r}

hourly_total %>% 
  group_by(time) %>% 
  summarize(average_steps=mean(step_total)) %>%
  ggplot(mapping = aes(x=time,y=average_steps,fill=average_steps))+
  geom_col()+
  labs(title = "Average hourly steps throughout the day", x="Hour of the Day", y="Average Steps") +
  guides(fill=guide_legend(title="Scale"))+
  theme(axis.title.x=element_text(colour="red"))+
   theme(axis.title.y=element_text(colour="red"))+
   theme(plot.title = element_text(color = "red"))+
   coord_flip()
 
```
<br>
* **11am to 7pm is most time active.**

<span style="color: red;">**Checking user groups distribution to levels** </span>
```{r}
#categorize users according to how many days they use their tracker
#disregard step counts less than 150 since we'll assume that tracker wasnt used
user_groups <- Daily_Activity %>% 
  filter(total_steps>150) %>% 
  group_by(id) %>% 
  summarize(activity_date=sum(n())) %>% 
  rename(days_in_use=activity_date)%>% 
  mutate(usage = case_when(
  days_in_use >= 1 & days_in_use <= 14 ~ "Low",
  days_in_use >= 15 & days_in_use <= 21 ~ "Moderate", 
  days_in_use >= 22 & days_in_use <= 31 ~ "High")) %>% 
  mutate(usage = factor(usage, level = c('Low','Moderate','High')))
#active levels among user groups
#make new dataframe so that your daily activity data also has a column for user group
usage_2 <- daily_sleep_activity %>% 
  left_join(user_groups, by ="id")
#new dataframe
active_user <- usage_2 %>% 
  group_by(usage) %>%
  summarise(very_active=round(mean(very_active_minutes),0),
            fairly_active=round(mean(fairly_active_minutes),0),
            lightly_active=round(mean(lightly_active_minutes),0))
 #add total column so you can do percentages 
 active_user <- active_user %>% 
   mutate(total=rowSums(active_user[,2:4]))
  

#reshape into long type so i can plot it 
active_user_long <- pivot_longer(active_user,2:4,names_to = "activity",
                                 values_to = "average_minutes")
#add percentage for each usage case using this pipeline
active_user_long <- active_user_long %>% 
  mutate(percentage=case_when(
    usage=="Low"~average_minutes/total,
    usage=="Moderate"~average_minutes/total,
    usage=="High"~average_minutes/total)) %>% 
  mutate(percentage = scales::percent(percentage)) 
    
#plot average actives minutes by user group and level of activity
ggplot(data=active_user_long)+
  geom_col(aes(x=usage,y=average_minutes,group=usage,fill=activity))+
  labs(title="Average active minutes by user group, level of activity",x="User Group",
       y="Average Minutes")+
  geom_text_repel(aes(x=usage,y=average_minutes,label=percentage),color="black",size=3.25)+
  guides(fill=guide_legend(title="Level of activity"))+
  theme(axis.title.x=element_text(colour="red"))+
   theme(axis.title.y=element_text(colour="red"))+
   theme(plot.title = element_text(color = "red"))+
  coord_flip()
```



<span style="color: red;">**Analyzing Weight** </span>

```{r}
#find out how many users from each user group tracked their weight
weight2 <- Weight %>% 
  left_join(usage_2,by=c("id")) %>% 
  select(id,weight_pounds,usage) %>% 
  group_by(id,usage) %>% 
  distinct() %>%
  drop_na() %>% 
  #important to write keep below so that df can stay grouped and i can use tally
  #by grouping by usage again
  summarise(avg_weight=round(mean(weight_pounds),2),.groups = "keep") %>% 
  group_by(usage) %>% 
  tally()


#plot bar graph showing number of users tracking weight
ggplot(weight2,aes(x=usage,y=n,fill=usage))+
  geom_col()+
  coord_flip()+
  theme_minimal()+
  labs(title = "Numbers of users tracking their weight",subtitle="by Usage Group",
       x="Usage Group",y="Number of Users")+
  theme(axis.title.x=element_text(colour="red"))+
   theme(axis.title.y=element_text(colour="red"))+
   theme(plot.title = element_text(color = "red"))+
   theme(plot.subtitle = element_text(color = "purple"))+
  geom_text_repel(aes(label=n),vjust=1.5)+
  guides(fill="none")
```


<span style="color: red;">**Analyzing Intenseties** </span>
```{r}
#intensity analysis by usage group, throughout the week
intensity2 <- hourly_total %>% 
  left_join(usage_2,by =c('id','day')) %>% 
  filter(total_intensity>0) %>% 
  drop_na() %>% 
  group_by(usage,day) %>% 
  summarise(intensity=round(mean(total_intensity),2))

#reorder columns so that day is next to date
hourly_total <- hourly_total[,c(1,2,8,3:7)]
#level order to make days appear in order
level_order <- c("Monday", "Tuesday", 
                 "Wednesday", "Thursday",
                 "Friday", "Saturday", "Sunday")


#plot intensities by usage group thruought week
ggplot(intensity2,aes(x=factor(day,level=level_order),y=intensity,fill=usage))+
  geom_col()+
 
  coord_flip()+
  theme_minimal()+
  labs(title = "Intensity throughout the week",
       subtitle = "by Usage Group",
       x="Day",y="Intensity")+
  guides(fill="none")+
  facet_wrap(~usage)+
  theme(axis.title.x=element_text(colour="red"))+
   theme(axis.title.y=element_text(colour="red"))+
   theme(plot.title = element_text(color = "red"))+
   theme(plot.subtitle = element_text(color = "purple"))
```



# **<span style="color: purple;">Act (Data) </span>**

<span style="color: purple;">**Discussion**: </span>
After analyzing how people use their smart fitness device, we were able to to learn about trends and as well as make data driven decisions to answer the 3 guiding questions to this study:

*  1-What are some trends in smart device usage?
*  2-How could these trends apply to Bellabeat customers?
*  3-How could these trends help influence Bellabeat marketing strategy?

<span style="color: purple;">**Key findings**: </span>
<br>

*  Usage of the smart device is higher during mid-week from Tuesday to Friday.

*  Most users used the activity tracking feature.

*  Most used features: 1-Steps 2-Sleep

*  (73%) of users are considered high usage users.

*  7500 steps being completed by most of users.

*  High usage users get their 8 hours of sleep recommended.

*  Features that needs some effort by users to enter their info into were less used.

<br>

<span style="color: purple;">**Limitations**: </span>
<br>

* Data was limited to 33 users.(Small Sample)
* Missing data from each feature.
* Collect bigger data about users, and add more users and metrics.

<span style="color: purple;">**Recommendations**: </span>
<br>

* Set up a notification system for users to be reminded to enter their information when needed.
* Categorize the target audience into 3 groups:

  1- <7000 steps --> Newly interested users.
  <br>
  2- 7000 <--> 9,999 steps --> Users with a good health/fitness base.
  <br>
  3- 10000+ steps --> Athletic users.
  
* Improve the heartrate monitor feature and make it more user friendly.
* Setting up personal goals for users when the start using the application.
* Reward active users by implementing a virtual tokenazition system.
* Teach users more about sleeping habbits and how important it is to get effecient amounts of sleep.



